services:
  ecommerce-db:
    volumes:
      - ecommerce:/var/lib/postgresql/ecommerce
    image: postgres:16.2
    container_name: e-commerce-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
volumes:
  ecommerce:
