services:
  ecommerce-db:
    volumes:
      - ecommerce:/var/lib/postgresql/ecommerce
    image: postgres:16.2
    container_name: ecommerce-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  # ecommerce-cms:
  #   build: .
  #   ports:
  #     - "3010:3000"
  #   environment:
  #     DATABASE_URL: ${DATABASE_URL}
  #   depends_on:
  #     ecommerce-db:
  #       condition: service_healthy

volumes:
  ecommerce:
